# spring.cloud.nacos.discovery。*的配置应该放置到application.yml /属性中。
# spring.cloud.nacos.config。*的配置应该放置到bootstrap.yml/properties中。

server:
  port: 9001
spring:
  application:
    # 应用名称
    name: ss-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://m.hejinyo.cn:3306/ss-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: redhat
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: m.hejinyo.cn
    port: 6388
    password: redhat
    database: 0