# spring.cloud.nacos.discovery。*的配置应该放置到application.yml /属性中。
# spring.cloud.nacos.config。*的配置应该放置到bootstrap.yml/properties中。
server:
  port: 9010
spring:
  application:
    # 应用名称
    name: ss-admin
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://m.hejinyo.cn:3306/ss-admin?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: redhat
    hikari:
      idle-timeout: 30000
      connection-timeout: 10000
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://hejinyo.com:9001