spring:
  application:
    name: ss-gateway-server
  cloud:
    gateway:
      routes:
        - id: hejinyo
          uri: http://m.hejinyo.cn
          predicates:
            - Path=/hejinyo/**

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://hejinyo:password@localhost:8000/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 10
  instance:
    hostname: ss-gateway
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 20