server:
  port: 8100
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  application:
    # 应用名称
    name: ss-auth-server
  redis:
    host: m.hejinyo.cn
    port: 6388
    password: redhat
    database: 1

eureka:
  client:
    service-url:
      defaultZone: http://hejinyo:password@localhost:8000/eureka
    # 缓存清单每隔30秒跟新一次
    registry-fetch-interval-seconds: 5
  instance:
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 30
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 90
    # 实例使用ip进行访问
    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${server.port}
    #状态页面和健康指标
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health

# Feign 开启 Hystrix
feign:
  hystrix:
    enabled: true

# 超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
