# spring.cloud.nacos.discovery。*的配置应该放置到application.yml /属性中。
# spring.cloud.nacos.config。*的配置应该放置到bootstrap.yml/properties中。

server:
  port: 8083
  servlet:
    context-path: /ui
security:
  oauth2:
    client:
      clientId: userservice3
      clientSecret: 1234
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      scope: FOO
    resource:
      jwt:
        key-value: |
          -----BEGIN CERTIFICATE-----
          MIIDZzCCAk+gAwIBAgIEN8Fw0jANBgkqhkiG9w0BAQsFADBjMQswCQYDVQQGEwJD
          TjELMAkGA1UECBMCU0gxCzAJBgNVBAcTAlNIMRIwEAYDVQQKEwlsb2NhbGhvc3Qx
          EjAQBgNVBAsTCWxvY2FsaG9zdDESMBAGA1UEAxMJbG9jYWxob3N0MCAXDTIxMTAy
          NzAyNTA0OFoYDzIxMjExMDAzMDI1MDQ4WjBjMQswCQYDVQQGEwJDTjELMAkGA1UE
          CBMCU0gxCzAJBgNVBAcTAlNIMRIwEAYDVQQKEwlsb2NhbGhvc3QxEjAQBgNVBAsT
          CWxvY2FsaG9zdDESMBAGA1UEAxMJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEF
          AAOCAQ8AMIIBCgKCAQEAtmS3bjpNcghkhF1ujmDcGA2wqDcKuNUl5EamyYdMkHPr
          OzIGE70nUz85aBGT4FPVIY/zd/fVNaLxlJNVlyneEROmS4LPbZOCTHVTBwmxxu8C
          1GavZFbO9BnVCrvd3wMMT9etnYWXbk/PrWRTpMOrNIjAkzxV1b1llRIK5RsTKiFp
          /+EnzibcW6QJ2wBkDYYCN2IJqRFiGvqpc8bimmBThbtA8AUa2UzUMjSit5HRfb6T
          5coY/7D6JHwqcVmWdAhWXbOW8FctafPSIppUAjImkCP6IbLNIMYwVCiMi4ogLSgu
          SDkg6s+YtC36oG/tMRbtC7KnPHVuoLFs0zupKXvIzQIDAQABoyEwHzAdBgNVHQ4E
          FgQUKWQGJ5cgm94fpaSQkQUSBcFsa+IwDQYJKoZIhvcNAQELBQADggEBACAhx7Al
          5UkA06SP7JYYyBXBVXPNtRZ8VwzkwBvxBaMpwpUNkITW1vDmsy9nHSv87Mo8mXqR
          YiQZTU7wM3k9uzuO9i06W7ONjbR1jVfgbfdXSoRCexsztNTo72xJQkVPiOIMXcD+
          vfrr3KfxU6Zykp+rC6PIVk8NeKf1sU55SK4gwwN6dIePHr7qFU/Gf//kcxNnrc0r
          zXqpZ9breqfLo81jRTSPRN+1tpbhbM2JtpeN4UIh0beiMboVJftCzF5tR0p6fa5r
          bAxqsfiX2Ceujwa7OtduTGTDulqGulujMTjyx4aNC1uixhVy9va/VIyHslrRXj3R
          3w5vwQwlbVJ2QCo=
          -----END CERTIFICATE-----
spring:
  thymeleaf:
    cache: false
  application:
    # 应用名称
    name: client-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://m.hejinyo.cn:3306/ss-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: redhat
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 当前环境对应的 profile
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: ss-client